app/blueprints/events.py
import random
from datetime import datetime
from this import s
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session
from flask_mail import Message
from app.blueprints.admin import show_all_user
from app.blueprints.forms import EventForm, TodoListForm
import string
from app import db, mail
from werkzeug.security import generate_password_hash, check_password_hash

from app.models import EmailCaptchaModel, UserModel, EventModel, TodoListModel

# 注册了一个bp，名字叫event，前置路径是/event
bp = Blueprint("event", __name__, url_prefix="/event")

@bp.route('/add_event', methods=['POST', 'GET'])
def add_event():
    if request.method == 'GET':
        return render_template('add_event.html')
    else:
        user_id = session.get('id')
        user=UserModel.query.filter(UserModel.id==user_id).first()
        # print(user_id)
        id = request.values.get("list_id")
        form = EventForm(request.form)
        if form.validate():
            title = form.event_name.data
            content = form.event_description.data
            setting_date_all = request.values.get("event_finish_date")
            setting_day = setting_date_all.split('-')
            setting_year , setting_month , setting_date = setting_day
            setting_time = request.values.get("event_finish_time")
            url = request.values.get("event_url")
            if len(url)<7:
                print("url:", url)
                url = url_for("index", username=user.username, id=user.id)
            print("url")
            # print(setting_year, setting_month, setting_date)
            label = request.values.get("label")
            # print(setting_time, type(setting_time))
            setting_time = datetime.strptime(setting_time, "%H:%M").time()
            duration = (datetime.strptime(setting_date_all, "%Y-%m-%d")-datetime.now()).days + 1
            todo_list = TodoListModel.query.filter(TodoListModel.id==id).first()
            # print(label, duration)
            if todo_list:
                event = EventModel(
                    gone_days = 0,
                    user_id = user_id,
                    title=title,
                    content=content,
                    setting_year=setting_year,
                    setting_month=setting_month,
                    setting_date=setting_date,
                    setting_time=setting_time,
                    todo_list_id=id,
                    label=label,
                    create_datetime=datetime.now(),
                    duration = duration,
                    url = url
                )
                db.session.add(event)
                db.session.commit()
                return redirect(url_for("index", username=user.username, id=user.id))
            else:
                return jsonify(code=400, message = "Invalid user")
        else:
            return jsonify(code=400, message = "Invalid form")

@bp.route('/load_event', methods=['POST'])
def load_event():
    user_id = session.get('id')
    user = UserModel.query.filter(UserModel.id==user_id).first()
    list_id = request.values.get("list_id")
    # print("list id:",list_id)
    com = '0'
    events = EventModel.query.filter(EventModel.todo_list_id==list_id and EventModel.finished==com).order_by("duration").all()
    for event in events:
        event.gone_days = (datetime.now()-event.create_datetime).days
    try:
        db.session.commit()
        return jsonify({'code':200, 'message':render_template('show_event.html',user=user, events=events, list_id = 0, com = com)})
    except Exception as e:
        db.session.rollback()
        return jsonify({'code':400, 'message' :str(e)})

@bp.route('/load_event_label', methods=['POST'])
def load_event_label():
    user_id = session.get('id')
    user = UserModel.query.filter(UserModel.id==user_id).first()
    label = request.values.get("label")
    com = '0'
    u_events = EventModel.query.filter(EventModel.user_id==user_id)
    events = u_events.filter(EventModel.label==label, EventModel.finished==com).all()
    for event in events:
        event.gone_days = (datetime.now()-event.create_datetime).days
    try:
        db.session.commit()
        return jsonify({'code':200, 'message':render_template('show_event.html',user=user, events=events, list_id = 0, com = com)})
    except Exception as e:
        db.session.rollback()
        return jsonify({'code':400, 'message' :str(e)})

@bp.route('/completed', methods=['POST'])
def completed():
    user_id = session.get('id')
    user = UserModel.query.filter(UserModel.id==user_id).first()
    com = request.values.get('com')
    user_e = EventModel.query.filter(EventModel.user_id==user.id)
    events = user_e.filter(EventModel.finished==com)
    for event in events:
        event.gone_days = (datetime.now()-event.create_datetime).days
    try:
        db.session.commit()
        return jsonify({'code':200, 'message':render_template('show_event.html',user=user, events=events, list_id = 0, com = com)})
    except Exception as e:
        db.session.rollback()
        return jsonify({'code':400, 'message' :str(e)})

@bp.route('/add_todolist', methods=['POST', 'GET'])
def add_todolist():
    if request.method == 'GET':
        return render_template('add_todolist.html')
    else:
        id = session.get('id')
        form = TodoListForm(request.form)
        if form.validate():
            list_name = form.todo_list_name.data
            user = UserModel.query.filter(UserModel.id == id).first()
            if user:
                todo_list = TodoListModel(
                    user_id = id, list_name=list_name, limit=20
                )
                db.session.add(todo_list)
                db.session.commit()
                return redirect(url_for("index", username=user.username, id=user.id))
            else:
                return jsonify(code=400, message = "Invalid user")
        else:
            return jsonify(code=400, message = "Invalid form")

@bp.route('/load_todolist', methods=['GET'])
def load_todolist():
    id = session.get('id')
    user = UserModel.query.filter(id == id).first()
    print(id)
    todoLists = TodoListModel.query.filter(TodoListModel.user_id==id).all()
    lists = []
    for todoList in todoLists:
        lists.append({
            'id': todoList.id,
            'list_name': todoList.list_name,
        })
    return jsonify(code=200, message = lists)

@bp.route('/finished_event', methods=['POST'])
def finished_event():
    id = request.values.get('id')
    event = EventModel.query.filter(EventModel.id == id).first()
    list_id = event.todo_list_id
    if event:
        event.finished = True
        db.session.commit()
        return jsonify({"code": 200, "message": "Event finished!", "list_id":list_id})
    else:
        return jsonify({"code": 400, "message": "Invalid event id!"})

@bp.route('/delete_event', methods=['POST'])
def delete_event():
    id = request.values.get('id')
    event = EventModel.query.filter(EventModel.id== id).first()
    db.session.delete(event)
    try:
        db.session.commit()
        return jsonify({'code':200, 'message' :"Delete the event successfully!"})
    except Exception as e:
        db.session.rollbacks()
        return jsonify({'code': 400, 'message': str(e)})

@bp.route('/edit_event', methods=['POST'])
def edit_event():
    user_id = session.get('id')
    if user_id:
        user = UserModel.query.filter(UserModel.id == user_id).first()
        if user:
            form = EventForm(request.form)
            if form:
                event_id = request.values.get('event_id')
                event = EventModel.query.filter(EventModel.id == event_id)
                title = form.event_name.data
                content = form.event_description.data
                setting_date_all = request.values.get("event_finish_date")
                setting_day = setting_date_all.split('-')
                setting_year , setting_month , setting_date = setting_day
                setting_time = request.values.get("event_finish_time")
                print(setting_time)
                setting_time = setting_time.split(":")
                setting_hour = setting_time[0]
                setting_min = setting_time[1]
                print(setting_hour+":"+setting_min)
                setting_time = datetime.strptime(setting_hour+":"+setting_min, "%H:%M").time()
                label = request.values.get("label")
                duration = (datetime.strptime(setting_date_all, "%Y-%m-%d")-datetime.now()).days + 1
                event.update(
                    {
                        'title': title,
                        'content': content,
                        'setting_date': setting_date,
                        'setting_year': setting_year,
                        'setting_month': setting_month,
                        'setting_date': setting_date,
                        'setting_time': setting_time,
                        'label': label,
                        'duration': duration,
                    }
                )
                db.session.commit()
                return redirect(url_for("index", username=user.username, id=user.id))
            else:
                return jsonify(code=400, message="Invalid form")
        else:
            return jsonify(code=400, message = "Invalid user")
    else:
        return jsonify(code=400, message = "please re-login")

@bp.route('/load_calendar', methods=['GET'])
def calendar():
    return render_template('calendar.html')

@bp.route('/duedates', methods=['POST'])
def duedates():
    id = session.get('id')
    year = request.values.get("year")
    month = request.values.get("month")
    print(year, month)
    all_event = EventModel.query.filter(EventModel.user_id ==id)
    year_event = all_event.filter(EventModel.setting_year == year)
    event_month = year_event.filter(EventModel.setting_month==month).all()
    events = []
    dates = []
    for event in event_month:

app/blueprints/users.py
import random
from datetime import datetime
from this import s
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session
from flask_mail import Message
from app.blueprints.admin import show_all_user
from app.blueprints.forms import LoginForm, RegisterForm
import string
from app import db, mail
from werkzeug.security import generate_password_hash, check_password_hash

from app.models import EmailCaptchaModel, UserModel

# 注册了一个bp，名字叫user，前置路径是/user
bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        print(request.form)
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            register_datetime = datetime.now()
            hash_password = generate_password_hash(password)  # 存入hash形式的密码
            user = UserModel(
                email=email,
                username=username,
                password=hash_password,
                register_datetime=register_datetime
            )
            db.session.add(user)
            db.session.commit()
            print("注册成功")
            session['email'] = email
            session['password'] = password
            session.permanent = True
            return redirect(url_for("user.login"))
        else:
            print("注册失败")
            return redirect((url_for("user.register")))

@bp.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        print('get')
        email = session.get('email')
        password = session.get('password')
        if email != None and password != None:
            print("email:", email)
            print("password:", password)
            return render_template("login.html", email=email, password=password)
        else:
            return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = request.values.get("email")
            password = request.values.get("password")
            if email == "admin@admin.com" and password == "admin":
                return redirect(url_for("admin.show_all_user"))
            user_model = UserModel.query.filter_by(email=email).first()
            if user_model:
                if check_password_hash(user_model.password, password):
                    print("登录成功")
                    try:
                        print(datetime.now)
                        user_model.state = True  # 更新用户状态
                        # db.session.add(user_model)
                        db.session.commit()
                    except Exception as e:
                        db.session.rollback()
                        raise e
                    id = user_model.id
                    session["id"] = id
                    session["username"] = user_model.username
                    session.permanent = True
                    print("id in session:",session.get("id"))
                    admin = user_model.admin
                    if admin:
                        return redirect(url_for("admin.show_all_user"))
                    else:
                        # return jsonify({"code": 200})
                        return redirect(url_for("index", username=user_model.username, id=user_model.id))
                else:
                    # print(url_for("user.login"))
                    print("密码不正确")
                    return redirect(url_for("user.login", email=email, password=password))
            else:
                return jsonify({"code": 400, "message": "用户不存在"})
        else:
            # print(url_for("user.login"))
            print("not valid")
            return redirect(url_for("user.login"))


@bp.route('/logout', methods=['POST'])
def logout():
    id = session.get("id")
    print(id)
    user = UserModel.query.filter_by(id=id).first()
    if id:
        session.pop('id')
        user.state = False
        db.session.commit()
        return jsonify({"code": 200})
    else:
        return jsonify({"code": 400, "message": "登出失败"})


@bp.route('/captcha', methods=['POST'])
def get_captcha():
    email = request.values.get("email")
    operation = request.values.get("operation")
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters, 4))
    if email:
        print("验证码:" + captcha)
        message = Message(
            subject="[测试]测试验证码发送",
            recipients=[email],
            html=render_template(
                'captcha.html', operation=operation, captcha=captcha),
            charset='utf-8'
            # body="hi"
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        return jsonify({"code": 200})
    else:
        return jsonify({"code": 400, "message": "没有传递邮箱"})


@bp.route("/change_password", methods=['GET', 'POST'])
def change_password():
    if request.method == "GET":
        id = session.get('id')
        # print('change_password-id in session:',id)
        user = UserModel.query.filter_by(id=id).first()
        return render_template("change_password.html", user=user)
    else:
        try:
            id = session.get('id')
            user = UserModel.query.filter_by(id=id).first()
        except:
            return jsonify({"code": 400, "message": "session失效"})
        old_password = request.form.get('old_password')
        if not check_password_hash(user.password, old_password):
            return jsonify({"code": 400, "message": "密码不正确"})
        captcha = request.form.get("captcha")
        email = user.email
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if not captcha_model or captcha_model.captcha.lower() != captcha.lower():
            return jsonify({"code": 400, "message": "验证码不正确"})
        new_password = request.form.get("new_password")
        password_confirm = request.form.get("password_confirm")
        if not new_password == password_confirm:
            return jsonify({"code": 400, "message": "密码输入不一致"})
        hash_password = generate_password_hash(new_password)  # 存入hash形式的密码
        user.password = hash_password
        db.session.commit()
        print("修改密码成功")
        session.permanent = True
        return redirect(url_for("user.login", email=email))

app/templates/add_event.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>用户注册</title>
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <link href="../static/bootstrap-5.1.3-dist/css/bootstrap.min.css"></link>
    <script src="{{ url_for('static', filename='js/add_event.js') }}"></script>
  </head>
  <body>
    <form action="{{ url_for('event.add_event') }}" method="POST">
      <table>
        <tbody>
          <tr>
            <td>标题：</td>
            <td>
              <label>
                <input type="text" name="title" />
              </label>
            </td>
          </tr>
          <tr>
            <td>备注：</td>
            <td>
              <label>
                <textarea type="textarea" name="content"></textarea>
              </label>
            </td>
          </tr>
          <tr>
            <td>时间：</td>
            <td>
              <label>
                <input type="datetime-local" name="setting_datetime" />
              </label>
            </td>
          </tr>
          <tr>
            <td>
              <button class="btn btn-primary" id="add_event_btn" type="submit" value="{{id}}">添加事件</button>
            </td>
          </tr>
        </tbody>
      </table>
    </form>
    <script src="../static/bootstrap-5.1.3-dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/add_todolist.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add TodoList</title>
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <link href="{{url_for('static', filename='bootstrap-5.1.3-dist/css/bootstrap.min.css')}}" rel="stylesheet"></link>
    <script src="{{ url_for('static', filename='js/add_todolist.js') }}"></script>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-4">
          <form action="{{ url_for('event.add_todolist') }}" method="POST">
            <div class="md-3">
              <label class="from-label" for="todo_list_name">TodoList Name</label>
              <input type="text" class="from-control" id="todo_list_name" name="todo_list_name">
            </div>
            <div class="col-12 d-grid">
              <label class="form-label"></label>
              <button class="btn btn-primary" id="add_event_btn" type="submit">
                Add TodoList
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script src="../static/bootstrap-5.1.3-dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}{%endblock%}</title>
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <link href="{{url_for('static', filename='bootstrap-5.1.3-dist/css/bootstrap.min.css')}}" rel="stylesheet"></link>
    <link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet"></link>
  </head>
  <body>
    <div id="logo">
      <div id="hello">Welcome to </div>
      <div id="todo_list">MyTodoList</div>
      <img src="{{url_for('static', filename='picture/logo.png')}}" width="100%"/>
    </div>
    <div class="container">
      <div class="card">
        {% block form %}{% endblock %}
      </div>
    </div>
    <script src="../static/bootstrap-5.1.3-dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/change_password.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Page-Enter" content="blendTrans(Duration=2.0)" />
    <title>Change Password</title>
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static', filename='jquery/jquery.cookie.js') }}"></script>
    <link href="{{url_for('static', filename='bootstrap-5.1.3-dist/css/bootstrap.css')}}" rel="stylesheet"></link>
    <script src="{{ url_for('static', filename='js/change_password.js') }}"></script>
    <link href="{{ url_for('static', filename='css/change_password.css')}}" rel="stylesheet"></link>
  </head>
  <body>
    <div id="container">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light" id="navbar" value="{{user.id}}">
          <!-- jquery -->
        </nav>
        <div class="row">
          <div class="col-md-4">
          </div>
          <div class="col-md-4">
            <div class="card">
              <form action="{{ url_for('user.change_password') }}" method="POST">
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Please input the old password:</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" name="old_password">
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Please input the new password:</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" name="new_password">
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Please confirm your new password:</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" name="password_confirm">
                </div>
                <!-- <input type="hidden" class="form-control" id="email" name="email" value="{{user.email}}" /> -->
                <div class="md-3 row">
                  <label for="exampleCaptcha" class="form-label">Get captcha:</label>
                  <div class="col-6">
                    <input type="text" class="form-control" id="exampleCaptcha" name="captcha" />
                  </div>
                  <div class="col-6 d-grid">
                    <button type="button" class="btn btn-primary" id="captcha-btn" value="{{user.email}}">Get captcha</button>
                  </div>
                  <label class="form-label"></label>
                </div>
                <div class="col-12 d-grid">
                  <label class="form-label"></label>
                  <button type="submit" class="btn btn-primary">Change password</button>
                  <label class="form-label"></label>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="../static/bootstrap-5.1.3-dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/index.html
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Page-Enter" content="blendTrans(Duration=2.0)" />
    {% if title %}
    <title>MyTodoList</title>
    {% else %}
    <title>No title</title>
    {% endif %}
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static', filename='jquery/jquery.cookie.js') }}"></script>
    <script src="../static/popper/popper.min.js"></script>
    <link href="{{ url_for('static', filename='bootstrap-5.1.3-dist/css/bootstrap.css')}}" rel="stylesheet"></link>
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
    <link href="{{ url_for('static', filename='css/index.css')}}" rel="stylesheet"></link>
  </head>
  <body>
    <div id="container">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light" id="navbar" value="{{user.id}}">
          <!-- jquery -->
        </nav>
        <div class="row">
          <div class="col-md-3" id="nav_vertical" value="1">
            <nav class="navbar navbar-expand-lg navbar-light">
              <div class="container-fluid  flex-column ">
                <ul class="navbar-nav mb-2 mb-lg-0 flex-column" id="ver_nav">
                  <label from="from-label"><hr></label>
                  <div id="labels" class="button-group-vertical d-grid" data-toggle="buttons">
                    <input type="radio" name="todo_lists" aria-autocomplete="off" class="btn-check com-list-btn" id="completed_list" value="1"><label class="btn btn-outline-dark" for="completed_list">Completed</label><label class='form-label'></label>
                    <input type="radio" name="todo_lists" aria-autocomplete="off" class="btn-check com-list-btn" id="uncompleted_list" value="0"><label class="btn btn-outline-dark" for="uncompleted_list">Uncompleted</label><label class='form-label'></label>
                    <div id="todo_lists" class="button-group-vertical d-grid" data-toggle="buttons">
                      <label from="from-label"><hr></label>
                      <!-- ajax by jquery return the todo_lists here -->
                    </div>
                    <label from="from-label"><hr></label>
                    <input type='radio' name='todo_lists' autocomplete='off' class='btn-check label-list-btn' id="red_list" value="1"><label class='btn btn-outline-danger' for="red_list"><span class="badge bg-danger p-1 border border-light rounded-circle"> </span> Red</label><label class='form-label'></label>
                    <input type='radio' name='todo_lists' autocomplete='off' class='btn-check label-list-btn' id="blue_list" value="2"><label class='btn btn-outline-primary' for="blue_list"><span class="badge bg-primary p-1 border border-light rounded-circle"> </span> Blue</label><label class='form-label'></label>
                    <input type='radio' name='todo_lists' autocomplete='off' class='btn-check label-list-btn' id="yellow_list" value="3"><label class='btn btn-outline-warning' for="yellow_list"><span class="badge bg-warning p-1 border border-light rounded-circle"> </span> Yellow</label><label class='form-label'></label>
                    <input type='radio' name='todo_lists' autocomplete='off' class='btn-check label-list-btn' id="green_list" value="4"><label class='btn btn-outline-success' for="green_list"><span class="badge bg-success p-1 border border-light rounded-circle"> </span> Green</label><label class='form-label'></label>
                    <input type='radio' name='todo_lists' autocomplete='off' class='btn-check label-list-btn' id="other_list" value="5"><label class='btn btn-outline-secondary' for="other_list"><span class="badge bg-secondary p-1 border border-light rounded-circle"> </span> Other</label><label class='form-label'></label>
                    <label from="from-label"><hr></label>
                  </div>
                  <li class="nav-item d-grid">
                    <button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#TodoListModal" id="add_todolist_btn" value="{{ user.id }}">
                      + New TodoList
                    </button>
                  </li>
                  <label from="from-label"><hr></label>
                </ul>
              </div>
            </nav>
          </div>
          <div class="col-md-5" id="events">
            <!-- jquery 请求页面 -->
          </div>
          <div class="col-md-4" id="right_card" value="1">
            <ul class="nav nav-tabs">
              <li class="nav-item">
                <div class="calendar-btn btn active card" aria-current="page" id="calendar_nav">Calendar</div>
              </li>
              <li class="nav-item">
                <div class="calendar-btn btn card" aria-current="page" id="statis_nav">Statistics</div>
              </li>
            </ul>
            <div class="card" id="calendar">
              <!-- jquery 请求日历📅 -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="../static/bootstrap-5.1.3-dist/js/bootstrap.min.js"></script>
  </body>
  <div class="modal fade" id="TodoListModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content addlist">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Create a new TodoList</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <form id="form1" action="{{ url_for('event.add_todolist') }}" method="POST">
      <div class="modal-body">
        <div class="md-3">
          <label class="from-label" for="todo_list_name">TodoList Name</label>
          <input type="text" class="form-control" id="todo_list_name" name="todo_list_name" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-primary" id="add_event_btn" type="submit">
          Add TodoList
        </button>
      </div>
    </form>
    </div>
    </div>
  </div>
</html>

app/templates/login.html
{% extends 'base.html' %}
{%block title%}Login{%endblock%}
{% block form %}
<script src="{{ url_for('static', filename='js/login.js') }}"></script>
<form action="{{ url_for('user.login') }}" method="POST">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" value="{{ email }}">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password" value="{{ password }}">
  </div>
  <div class="col-12 d-grid">
    <label class="form-label"></label>
    <button type="submit" class="btn btn-primary">login</button>
    <label class="form-label"></label>
  </div>
  <div class="row">
    <label class="form-label"></label>
    <div class="col-6 d-grid">
      <button type="button" class="btn btn-outline-secondary" id="register_btn">Register now</button>
    </div>
    <div class="col-6 d-grid">
      <button type="button" class="btn btn-outline-secondary" id="forget_password_btn">Forgot password</button>
    </div>
  </div>
</form>
{% endblock %}

